apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
    - port: 3000
      targetPort: 3000
      name: frontend
    - port: 5000
      targetPort: 5000
      name: backend